### ISSUE TITLE
Add missing admin endpoints

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2182]
Query
- [x] `GET admin/v1/process-definitions`: https://github.com/Activiti/Activiti/issues/2149
- [x] `GET admin/v1/process-instances`
- [x] `GET admin/v1/tasks`
- [x] `GET admin/v1/tasks?parentTaskId={parentTaskId}`  (subtasks)
- [x] `GET admin/v1/tasks/{taskId}`
- [ ] `GET admin/v1/process-instances/${id}/model` https://github.com/Activiti/Activiti/issues/2389
- [x] `GET admin/v1/process-instances/${id}/variables`

Runtime Bundle
- [x] `GET admin/v1/process-instances/${id}/suspend`:https://github.com/Activiti/Activiti/issues/2150
- [x] `GET admin/v1/process-instances/${id}/resume`: https://github.com/Activiti/Activiti/issues/2151
- [ ] `DELETE admin/v1/process-instances/${id}` : https://github.com/Activiti/Activiti/issues/2369
- [ ] `DELETE admin/v1/process-instances/${id}/variables` https://github.com/Activiti/Activiti/issues/2390
- [ ] `PUT admin/v1/tasks/${taskId}` https://github.com/Activiti/Activiti/issues/2372
- [x] ~~`POST admin/v1/tasks/${id}/claim`~~ --> `POST admin/v1/tasks/${id}/assign`
- [ ] `POST admin/v1/tasks/${id}/complete` https://github.com/Activiti/Activiti/issues/2371
- [ ] `DELETE admin/v1/tasks/${id}` https://github.com/Activiti/Activiti/issues/2373

**Comment by salaboy** [comment]
@erdemedeiros is this one for admin as well -> POST /v1/tasks/${id}/claim

**Comment by salaboy** [comment]
@erdemedeiros I don't think that we need this one: POST admin/v1/tasks/${id}/claim

we should do that via task update sending the assignee that the admin wants to set. That should work, but we need to check the events. I would expect a TaskUpdated Event only..

**Comment by salaboy** [comment]
@erdemedeiros and this one: DELETE admin/v1/tasks/${id} should fail if the task belong to a process.. it should say something like.. delete the process instance and the task will be deleted for you.

**Comment by salaboy** [comment]
@erdemedeiros can you please link the new issues to this issue just for historical purposes.. 
but also close this one.. so we keep track of the smaller issues only

**Comment by erdemedeiros** [comment]
Closing this issue to keep track of smaller issues only.

**Comment by erdemedeiros** [comment]
All the links are already in the description of this issue (see unchecked ones).
